name: Publish Package

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HelpfulTypesAndExtensions
    permissions:
      contents: read  # Optional, defaults to read
      packages: write  # Grants write permission to packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Specify your .NET SDK version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack --configuration Release --no-build -o ./packages

      - name: Configure NuGet to use GitHub Packages
        run: |
          dotnet nuget add source --username DragoQCC --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DragoQCC/index.json"
        shell: bash

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./packages/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      